In [ ]:
from pokedex import main_pokemon_run

df, html_display = main_pokemon_run()

# Mostrar los primeros 10 Pokémon
df.head(10)
# Mostrar el HTML generado

Se obtuvieron 898 Pokémon

100%|██████████| 898/898 [26:59<00:00,  1.80s/it]

Se descargaron datos de 898 Pokémon

,Image,id,name,height,base_experience,weight,species
0,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png,1,bulbasaur,7,64,69,bulbasaur
1,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png,2,ivysaur,10,142,130,ivysaur
2,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png,3,venusaur,20,236,1000,venusaur
3,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png,4,charmander,6,62,85,charmander
4,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png,5,charmeleon,11,142,190,charmeleon
5,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png,6,charizard,17,240,905,charizard
6,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png,7,squirtle,5,63,90,squirtle
7,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png,8,wartortle,10,142,225,wartortle
8,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png,9,blastoise,16,239,855,blastoise
9,https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png,10,caterpie,3,39,29,caterpie

In [3]:
def image_formatter(im):
    return f'<img src="{im}">'

from IPython.display import HTML

HTML(df.head(10).to_html(formatters={'Image': image_formatter}, escape=False))